[package]
name = "day25"
version = "0.1.0"
authors = ["Roger G. Coram <psypherpunk@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "^0.1"