package main

import (
	"bufio"
	_ "embed"
	"fmt"
	"strconv"
	"strings"
)

//go:embed input.txt
var input string

func mixSecret(secret, value int) int {
	return secret ^ value
}

func pruneSecret(secret int) int {
	return secret % 16777216
}

func evolveSecret(secret int) int {
	result := secret * 64
	secret = mixSecret(secret, result)
	secret = pruneSecret(secret)

	result = secret / 32
	secret = mixSecret(secret, result)
	secret = pruneSecret(secret)

	result = secret * 2048
	secret = mixSecret(secret, result)
	secret = pruneSecret(secret)

	return secret
}

func PartOne(input string) int {
	scanner := bufio.NewScanner(strings.NewReader(input))

	secretNumbers := []int{}
	for scanner.Scan() {
		line := scanner.Text()
		secretNumber, err := strconv.Atoi(line)
		if err != nil {
			fmt.Println("invalid line:", line)
		}
		secretNumbers = append(secretNumbers, secretNumber)
	}

	sumSecretNumbers := 0
	for _, value := range secretNumbers {
		secret := value
		for i := 0; i < 2000; i++ {
			secret = evolveSecret(secret)
		}
		sumSecretNumbers += secret
	}

	return sumSecretNumbers
}

func PartTwo(input string) int {
	return 0
}

func main() {
	fmt.Println("What is the sum of the 2000th secret number generated by each buyer?", PartOne(input))

	fmt.Println("", PartTwo(input))
}
