[package]
name = "day18"
version = "0.1.0"
authors = ["Roger G. Coram <psypherpunk@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
parameterized = "^0.3"